name: Github Blog
on:
  push:
    branches: [ master ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: build and deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: OrangeGeeker/OrangeGeeker.github.io
        TARGET_BRANCH: master
        BUILD_SCRIPT: npm install && npm run build
        
